export const eventOptions  = [
    { text: "Conference", key: "CONFERENCE", value: "con" },
    { text: "Guest Lecture", key: "GUEST_LECTURE", value: "gue" },
    { text: "Seminar", key: "SEMINAR", value: "sem" },
    { text: "Short term course", key: "SHORT_TERM_COURSE", value: "stc" },
    { text: "Special lecture", key: "SPECIAL_LECTURE", value: "spl" },
    { text: "Talk", key: "TALK", value: "tlk" },
    { text: "Other", key: "OTHER", value: "oth" }
];

export const projectOptions = [
    { text: "Sponsored", key: "SPONSORED", value: "s" },
    { text: "Consultancy", key: "CONSULTANCY", value: "c" }
];

export const categoryOptions = [
    { text: "Conference", key: "CONFERENCE", value: "con"},
    { text: "Guest Lecture", key: "GUEST_LECTURE", value: "gue"},
    { text: "Seminar", key: "SEMINAR", value: "sem"},
    { text: "Short Term Course", key: "SHORT_TERM_COURSE", value: "stc"},
    { text: "Lecture", key: "LECTURE", value: "spl"},
    { text: "Special Talk", key: "SPECIAL_TALK", value: "tlk"},
    { text: "Other", key: "OTHER", value: "oth" }
]
export const roleOptions = [
    { text: "Organiser", key: "ORGANISER", value: "o" },
    { text: "Attendee", key: "ATTENDEE", value: "a" },
    { text: "Invitee", key: "INVITEE", value: "i" }
];

export const scopeOptions = [
    { text: "Departmental", key: "DEPARTMENTAL", value: "d" },
    { text: "Central", key: "CENTRAL", value: "c" },
    { text: "Institute", key: "INSTITUTE", value: "i" },
];

export const supervisionOptions = [
    { text: "Project", key: "PROJECT", value: "pro" },
    { text: "Doctorate", key: "DOCTORATE", value: "doc" }
];

export const phdOptions = [
    { text: "Fulltime", key: "FULLTIME", value: "f" },
    { text: "Parttime", key: "PARTTIME", value: "p" }
];

export const graduationOptions = [
    { text: "Matriculate", key: "MATRICULATE", value: "mat" },
    { text: "Intermediate", key: "INTERMEDIATE", value: "int" },
    { text: "Associate", key: "ASSOCIATE", value: "ass" },
    { text: "Graduate", key: "GRADUATE", value: "gra" },
    { text: "Postgraduate", key: "POSTGRADUATE", value: "pos" },
    { text: "Doctorate", key: "DOCTORATE", value: "doc" },
    { text: "Postdoctorate", key: "POSTDOCTORATE", value: "pdo" }
  ];

export const semesterOptions = [
    { text: "Spring", key: "SPRING", value: "s" },
    { text: "Autumn", key: "AUTUMN", value: "a" }
];

export const collaborationOptions = [
    { text: "Undergraduate", key: "UNDERGRADUATE", value: "ug" },
    { text: "Postgraduate", key: "POSTGRADUATE", value: "pg" },
    { text: "PhD", key: "DOCTORATE", value: "phd" },
    { text: "Research Project", key: "RESEARCH_PROJECT", value: "rp" },
    { text: "Other", key: "OTHER", value: "oth" }
];

export const countryOptions = [
    { text: "None", key: "None", value: "None"},
    { text: "Afghanistan", key: "Afghanistan", value: "Afghanistan" },
  { text: "Albania", key: "Albania", value: "Albania" },
  { text: "Algeria", key: "Algeria", value: "Algeria" },
  { text: "Andorra", key: "Andorra", value: "Andorra" },
  { text: "Angola", key: "Angola", value: "Angola" },
  { text: "Antigua and Barbuda", key: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { text: "Argentina", key: "Argentina", value: "Argentina" },
  { text: "Armenia", key: "Armenia", value: "Armenia" },
  { text: "Aruba", key: "Aruba", value: "Aruba" },
  { text: "Australia", key: "Australia", value: "Australia" },
  { text: "Austria", key: "Austria", value: "Austria" },
  { text: "Azerbaijan", key: "Azerbaijan", value: "Azerbaijan" },
  { text: "Bahamas", key: "Bahamas", value: "Bahamas" },
  { text: "Bahrain", key: "Bahrain", value: "Bahrain" },
  { text: "Bangladesh", key: "Bangladesh", value: "Bangladesh" },
  { text: "Barbados", key: "Barbados", value: "Barbados" },
  { text: "Belarus", key: "Belarus", value: "Belarus" },
  { text: "Belgium", key: "Belgium", value: "Belgium" },
  { text: "Belize", key: "Belize", value: "Belize" },
  { text: "Benin", key: "Benin", value: "Benin" },
  { text: "Bermuda", key: "Bermuda", value: "Bermuda" },
  { text: "Bhutan", key: "Bhutan", value: "Bhutan" },
  { text: "Bolivia", key: "Bolivia", value: "Bolivia" },
  { text: "Bosnia and Herzegovina", key: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { text: "Botswana", key: "Botswana", value: "Botswana" },
  { text: "Brazil", key: "Brazil", value: "Brazil" },
  { text: "Brunei", key: "Brunei", value: "Brunei" },
  { text: "Bulgaria", key: "Bulgaria", value: "Bulgaria" },
  { text: "Burkina Faso", key: "Burkina Faso", value: "Burkina Faso" },
  { text: "Burundi", key: "Burundi", value: "Burundi" },
  { text: "Cambodia", key: "Cambodia", value: "Cambodia" },
  { text: "Cameroon", key: "Cameroon", value: "Cameroon" },
  { text: "Canada", key: "Canada", value: "Canada" },
  { text: "Cape Verde", key: "Cape Verde", value: "Cape Verde" },
  { text: "Cayman Islands", key: "Cayman Islands", value: "Cayman Islands" },
  { text: "Central African Republic", key: "Central African Republic", value: "Central African Republic" },
  { text: "Chad", key: "Chad", value: "Chad" },
  { text: "Chile", key: "Chile", value: "Chile" },
  { text: "China", key: "China", value: "China" },
  { text: "Christmas Island", key: "Christmas Island", value: "Christmas Island" },
  { text: "Cocos Islands", key: "Cocos Islands", value: "Cocos Islands" },
  { text: "Colombia", key: "Colombia", value: "Colombia" },
  { text: "Comoros", key: "Comoros", value: "Comoros" },
  { text: "Congo", key: "Congo", value: "Congo" },
  { text: "Cook Islands", key: "Cook Islands", value: "Cook Islands" },
  { text: "Costa Rica", key: "Costa Rica", value: "Costa Rica" },
  { text: "Cote d'Ivoire", key: "Cote d'Ivoire", value: "Cote d'Ivoire" },
  { text: "Croatia", key: "Croatia", value: "Croatia" },
  { text: "Cuba", key: "Cuba", value: "Cuba" },
  { text: "Curacao", key: "Curacao", value: "Curacao" },
  { text: "Cyprus", key: "Cyprus", value: "Cyprus" },
  { text: "Czech Republic", key: "Czech Republic", value: "Czech Republic" },
  { text: "Denmark", key: "Denmark", value: "Denmark" },
  { text: "Djibouti", key: "Djibouti", value: "Djibouti" },
  { text: "Dominica", key: "Dominica", value: "Dominica" },
  { text: "Dominican Republic", key: "Dominican Republic", value: "Dominican Republic" },
  { text: "East Timor", key: "East Timor", value: "East Timor" },
  { text: "Ecuador", key: "Ecuador", value: "Ecuador" },
  { text: "Egypt", key: "Egypt", value: "Egypt" },
  { text: "El Salvador", key: "El Salvador", value: "El Salvador" },
  { text: "Equatorial Guinea", key: "Equatorial Guinea", value: "Equatorial Guinea" },
  { text: "Eritrea", key: "Eritrea", value: "Eritrea" },
  { text: "Estonia", key: "Estonia", value: "Estonia" },
  { text: "Ethiopia", key: "Ethiopia", value: "Ethiopia" },
  { text: "Falkland Islands", key: "Falkland Islands", value: "Falkland Islands" },
  { text: "Faroe Islands", key: "Faroe Islands", value: "Faroe Islands" },
  { text: "Fiji", key: "Fiji", value: "Fiji" },
  { text: "Finland", key: "Finland", value: "Finland" },
  { text: "France", key: "France", value: "France" },
  { text: "French Guiana", key: "French Guiana", value: "French Guiana" },
  { text: "French Polynesia", key: "French Polynesia", value: "French Polynesia" },
  { text: "French Southern Territories", key: "French Southern Territories", value: "French Southern Territories" },
  { text: "Gabon", key: "Gabon", value: "Gabon" },
  { text: "Gambia", key: "Gambia", value: "Gambia" },
  { text: "Georgia", key: "Georgia", value: "Georgia" },
  { text: "Germany", key: "Germany", value: "Germany" },
  { text: "Ghana", key: "Ghana", value: "Ghana" },
  { text: "Gibraltar", key: "Gibraltar", value: "Gibraltar" },
  { text: "Great Britain", key: "Great Britain", value: "Great Britain" },
  { text: "Greece", key: "Greece", value: "Greece" },
  { text: "Greenland", key: "Greenland", value: "Greenland" },
  { text: "Grenada", key: "Grenada", value: "Grenada" },
  { text: "Guadeloupe", key: "Guadeloupe", value: "Guadeloupe" },
  { text: "Guam", key: "Guam", value: "Guam" },
  { text: "Guatemala", key: "Guatemala", value: "Guatemala" },
  { text: "Guinea", key: "Guinea", value: "Guinea" },
  { text: "Guyana", key: "Guyana", value: "Guyana" },
  { text: "Haiti", key: "Haiti", value: "Haiti" },
  { text: "Hawaii", key: "Hawaii", value: "Hawaii" },
  { text: "Honduras", key: "Honduras", value: "Honduras" },
  { text: "Hong Kong", key: "Hong Kong", value: "Hong Kong" },
  { text: "Hungary", key: "Hungary", value: "Hungary" },
  { text: "Iceland", key: "Iceland", value: "Iceland" },
  { text: "Indonesia", key: "Indonesia", value: "Indonesia" },
  { text: "India", key: "India", value: "India" },
  { text: "Iran", key: "Iran", value: "Iran" },
  { text: "Iraq", key: "Iraq", value: "Iraq" },
  
    { text: "Ireland", key: "IRELAND", value: "Ireland" },
    { text: "Isle of Man", key: "ISLE_OF_MAN", value: "Isle of Man" },
    { text: "Israel", key: "ISRAEL", value: "Israel" },
    { text: "Italy", key: "ITALY", value: "Italy" },
    { text: "Jamaica", key: "JAMAICA", value: "Jamaica" },
    { text: "Japan", key: "JAPAN", value: "Japan" },
    { text: "Jordan", key: "JORDAN", value: "Jordan" },
    { text: "Kazakhstan", key: "KAZAKHSTAN", value: "Kazakhstan" },
    { text: "Kenya", key: "KENYA", value: "Kenya" },
    { text: "Kiribati", key: "KIRIBATI", value: "Kiribati" },
    { text: "North Korea", key: "NORTH_KOREA", value: "North Korea" },
    { text: "South Korea", key: "SOUTH_KOREA", value: "South Korea" },
    { text: "Kuwait", key: "KUWAIT", value: "Kuwait" },
    { text: "Kyrgyzstan", key: "KYRGYZSTAN", value: "Kyrgyzstan" },
    { text: "Laos", key: "LAOS", value: "Laos" },
    { text: "Latvia", key: "LATVIA", value: "Latvia" },
    { text: "Lebanon", key: "LEBANON", value: "Lebanon" },
    { text: "Lesotho", key: "LESOTHO", value: "Lesotho" },
    { text: "Liberia", key: "LIBERIA", value: "Liberia" },
    { text: "Libya", key: "LIBYA", value: "Libya" },
    { text: "Liechtenstein", key: "LIECHTENSTEIN", value: "Liechtenstein" },
    { text: "Lithuania", key: "LITHUANIA", value: "Lithuania" },
    { text: "Luxembourg", key: "LUXEMBOURG", value: "Luxembourg" },
    { text: "Macau", key: "MACAU", value: "Macau" },
    { text: "Macedonia", key: "MACEDONIA", value: "Macedonia" },
    { text: "Madagascar", key: "MADAGASCAR", value: "Madagascar" },
    { text: "Malaysia", key: "MALAYSIA", value: "Malaysia" },
    { text: "Malawi", key: "MALAWI", value: "Malawi" },
    { text: "Maldives", key: "MALDIVES", value: "Maldives" },
    { text: "Mali", key: "MALI", value: "Mali" },
    { text: "Malta", key: "MALTA", value: "Malta" },
    { text: "Marshall Islands", key: "MARSHALL ISLANDS", value: "Marshall Islands" },
    { text: "Martinique", key: "MARTINIQUE", value: "Martinique" },
    { text: "Mauritania", key: "MAURITANIA", value: "Mauritania" },
    { text: "Mauritius", key: "MAURITIUS", value: "Mauritius" },
    { text: "Mayotte", key: "MAYOTTE", value: "Mayotte" },
    { text: "Mexico", key: "MEXICO", value: "Mexico" },
    { text: "Midway Islands", key: "MIDWAY ISLANDS", value: "Midway Islands" },
    { text: "Moldova", key: "MOLDOVA", value: "Moldova" },
    { text: "Monaco", key: "MONACO", value: "Monaco" },
    { text: "Mongolia", key: "MONGOLIA", value: "Mongolia" },
    { text: "Montserrat", key: "MONTSERRAT", value: "Montserrat" },
    { text: "Morocco", key: "MOROCCO", value: "Morocco" },
    { text: "Mozambique", key: "MOZAMBIQUE", value: "Mozambique" },
    { text: "Myanmar", key: "MYANMAR", value: "Myanmar" },
    { text: "Nambia", key: "NAMBIA", value: "Nambia" },
    {text: "Nauru", key: "NAURU", value: "Nauru" },
    { text: "Nepal", key: "NEPAL", value: "Nepal" },
    { text: "Netherlands Antilles", key: "NETHERLANDS_ANTILLES", value: "Netherlands Antilles" },
    { text: "Netherlands", key: "NETHERLANDS", value: "Netherlands" },
    { text: "Nevis", key: "NEVIS", value: "Nevis" },
    { text: "New Caledonia", key: "NEW_CALEDONIA", value: "New Caledonia" },
    { text: "New Zealand", key: "NEW_ZEALAND", value: "New Zealand" },
    { text: "Nicaragua", key: "NICARAGUA", value: "Nicaragua" },
    { text: "Niger", key: "NIGER", value: "Niger" },
    { text: "Nigeria", key: "NIGERIA", value: "Nigeria" },
    { text: "Niue", key: "NIUE", value: "Niue" },
    { text: "Norfolk Island", key: "NORFOLK_ISLAND", value: "Norfolk Island" },
    { text: "Norway", key: "NORWAY", value: "Norway" },
    { text: "Oman", key: "OMAN", value: "Oman" },
    { text: "Pakistan", key: "PAKISTAN", value: "Pakistan" },
    { text: "Palau Island", key: "PALAU_ISLAND", value: "Palau Island" },
    { text: "Palestine", key: "PALESTINE", value: "Palestine" },
    { text: "Panama", key: "PANAMA", value: "Panama" },
    { text: "Papua New Guinea", key: "PAPUA_NEW_GUINEA", value: "Papua New Guinea" },
    { text: "Paraguay", key: "PARAGUAY", value: "Paraguay" },
    { text: "Peru", key: "PERU", value: "Peru" },
    { text: "Philippines", key: "PHILIPPINES", value: "Philippines" },
    { text: "Pitcairn Island", key: "PITCAIRN_ISLAND", value: "Pitcairn Island" },
    { text: "Poland", key: "POLAND", value: "Poland" },
    { text: "Portugal", key: "PORTUGAL", value: "Portugal" },
    { text: "Puerto Rico", key: "PUERTO_RICO", value: "Puerto Rico" },
    { text: "Qatar", key: "QATAR", value: "Qatar" },
    { text: "Republic of Montenegro", key: "REPUBLIC_OF_MONTENEGRO", value: "Republic of Montenegro" },
    { text: "Republic of Serbia", key: "REPUBLIC_OF_SERBIA", value: "Republic of Serbia" },
    { text: "Reunion", key: "REUNION", value: "Reunion" },
    { text: "Romania", key: "ROMANIA", value: "Romania" },
    { text: "Russia", key: "RUSSIA", value: "Russia" },
    { text: "Rwanda", key: "RWANDA", value: "Rwanda" },
    { text: "St Bartholemy", key: "ST_BARTHOLEMY", value: "St Bartholemy" },
    { text: "St Eustatius", key: "ST_EUSTATIUS", value: "St Eustatius" },
    { text: "St Helena", key: "ST_HELENA", value: "St Helena" },
    { text: "St Kitts-Nevis", key: "ST_KITTS_NEVIS", value: "St Kitts-Nevis" },
    { text: "St Lucia", key: "ST_LUCIA", value: "St Lucia" },
    { text: "St Maarten", key: "ST_MAARTEN", value: "St Maarten" },
    { text: "St Pierre and Miquelon", key: "ST_PIERRE_AND_MIQUELON", value: "St Pierre and Miquelon" },
    { text: "St Vincent and Grenadines", key: "ST_VINCENT_AND_GRENADINES", value: "St Vincent and Grenadines" },
    { text: "Saipan", key: "SAIPAN", value: "Saipan" },
    { text: "Samoa", key: "SAMOA", value: "Samoa" },
    { text: "Samoa American", key: "SAMOA_AMERICAN", value: "Samoa American" },
    { text: "San Marino", key: "SAN_MARINO", value: "San Marino" },
    { text: "Sao Tome and Principe", key: "SAO_TOME_AND_PRINCIPE", value: "Sao Tome and Principe" },
    { text: "Saudi Arabia", key: "SAUDI_ARABIA", value: "Saudi Arabia" },
    { text: "Senegal", key: "SENEGAL", value: "Senegal" },
    { text: "Seychelles", key: "SEYCHELLES", value: "Seychelles" },
    { text: "Sierra Leone", key: "SIERRA_LEONE", value: "Sierra Leone" },
    { text: "Singapore", key: "SINGAPORE", value: "Singapore" },
    { text: "Slovakia", key: "SLOVAKIA", value: "Slovakia" },
    { text: "Slovenia", key: "SLOVENIA", value: "Slovenia" },
    { text: "Solomon Islands", key: "SOLOMON_ISLANDS", value: "Solomon Islands" },
    { text: "Somalia", key: "SOMALIA", value: "Somalia" },
    { text: "South Africa", key: "SOUTH_AFRICA", value: "South Africa" },
    { text: "Spain", key: "SPAIN", value: "Spain" },
    { text: "Sri Lanka", key: "SRI_LANKA", value: "Sri Lanka" },
    { text: "Sudan", key: "SUDAN", value: "Sudan" },
    { text: "Suriname", key: "SURINAME", value: "Suriname" },
    { text: "Swaziland", key: "SWAZILAND", value: "Swaziland" },
    { text: "Sweden", key: "SWEDEN", value: "Sweden" },
    { text: "Switzerland", key: "SWITZERLAND", value: "Switzerland" },
    { text: "Syria", key: "SYRIA", value: "Syria" },
    { text: "Tahiti", key: "TAHITI", value: "Tahiti" },
    { text: "Taiwan", key: "TAIWAN", value: "Taiwan" },
    { text: "Tajikistan", key: "TAJIKISTAN", value: "Tajikistan" },
    { text: "Tanzania", key: "TANZANIA", value: "Tanzania" },
    { text: "Thailand", key: "THAILAND", value: "Thailand" },
    { "text": "Togo", "key": "TOGO", "value": "Togo" },
    { "text": "Tokelau", "key": "TOKELAU", "value": "Tokelau" },
    { "text": "Tonga", "key": "TONGA", "value": "Tonga" },
    { "text": "Trinidad and Tobago", "key": "TRINIDAD_AND_TOBAGO", "value": "Trinidad and Tobago" },
    { "text": "Tunisia", "key": "TUNISIA", "value": "Tunisia" },
    { "text": "Turkey", "key": "TURKEY", "value": "Turkey" },
    { "text": "Turkmenistan", "key": "TURKMENISTAN", "value": "Turkmenistan" },
    { "text": "Turks and Caicos Is", "key": "TURKS_AND_CAICOS_IS", "value": "Turks and Caicos Is" },
    { "text": "Tuvalu", "key": "TUVALU", "value": "Tuvalu" },
    { "text": "Uganda", "key": "UGANDA", "value": "Uganda" },
    { "text": "United Kingdom", "key": "UNITED_KINGDOM", "value": "United Kingdom" },
    { "text": "Ukraine", "key": "UKRAINE", "value": "Ukraine" },
    { "text": "United Arab Emirates", "key": "UNITED_ARAB_EMIRATES", "value": "United Arab Emirates" },
    { "text": "United States of America", "key": "UNITED_STATES_OF_AMERICA", "value": "United States of America" },
    { "text": "Uruguay", "key": "URUGUAY", "value": "Uruguay" },
    { "text": "Uzbekistan", "key": "UZBEKISTAN", "value": "Uzbekistan" },
    { "text": "Vanuatu", "key": "VANUATU", "value": "Vanuatu" },
    { "text": "Vatican City State", "key": "VATICAN_CITY_STATE", "value": "Vatican City State" },
    { "text": "Venezuela", "key": "VENEZUELA", "value": "Venezuela" },
    { "text": "Vietnam", "key": "VIETNAM", "value": "Vietnam" },
    { "text": "Virgin Islands (Brit)", "key": "VIRGIN_ISLANDS_BRIT", "value": "Virgin Islands (Brit)" },
    { "text": "Virgin Islands (USA)", "key": "VIRGIN_ISLANDS_USA", "value": "Virgin Islands (USA)" },
    { "text": "Wake Island", "key": "WAKE_ISLAND", "value": "Wake Island" },
    { "text": "Wallis and Futuna Is", "key": "WALLIS_AND_FUTUNA_IS", "value": "Wallis and Futuna Is" },
    { "text": "Yemen", "key": "YEMEN", "value": "Yemen" },
    { "text": "Zaire", "key": "ZAIRE", "value": "Zaire" },
    { "text": "Zambia", "key": "ZAMBIA", "value": "Zambia" },
    { "text": "Zimbabwe", "key": "ZIMBABWE", "value": "Zimbabwe" },
    { "text": "Korea", "key": "KOREA", "value": "Korea" },
    { "text": "Serbia", "key": "SERBIA", "value": "Serbia" }
]

let list = {};
for (let index in graduationOptions) {
list[graduationOptions[index]["value"]] = graduationOptions[index]["text"];
}

export const graduationOptionsMap = list;

for (let index in supervisionOptions) {
list[supervisionOptions[index]["value"]] = supervisionOptions[index]["text"];
}

export const supervisionOptionsMap = list;
  
export const reduceValueToText = (value, object) => {
    return value == object.value ? object.text : value;
}