export const eventOptions  = [
    { text: "Conference", key: "CONFERENCE", value: "con" },
    { text: "Guest Lecture", key: "GUEST_LECTURE", value: "gue" },
    { text: "Seminar", key: "SEMINAR", value: "sem" },
    { text: "Short term course", key: "SHORT_TERM_COURSE", value: "stc" },
    { text: "Special lecture", key: "SPECIAL_LECTURE", value: "spl" },
    { text: "Talk", key: "TALK", value: "tlk" },
    { text: "Other", key: "OTHER", value: "oth" }
];

export const projectOptions = [
    { text: "Sponsored", key: "SPONSORED", value: "s" },
    { text: "Consultancy", key: "CONSULTANCY", value: "c" }
];

export const categoryOptions = [
    { text: "Conference", key: "CONFERENCE", value: "con"},
    { text: "Guest Lecture", key: "GUEST_LECTURE", value: "gue"},
    { text: "Seminar", key: "SEMINAR", value: "sem"},
    { text: "Short Term Course", key: "SHORT_TERM_COURSE", value: "stc"},
    { text: "Lecture", key: "LECTURE", value: "spl"},
    { text: "Special Talk", key: "SPECIAL_TALK", value: "tlk"},
    { text: "Other", key: "OTHER", value: "oth" }
]
export const roleOptions = [
    { text: "Organiser", key: "ORGANISER", value: "o" },
    { text: "Attendee", key: "ATTENDEE", value: "a" },
    { text: "Invitee", key: "INVITEE", value: "i" }
];

export const scopeOptions = [
    { text: "Departmental", key: "DEPARTMENTAL", value: "d" },
    { text: "Central", key: "CENTRAL", value: "c" },
    { text: "Institute", key: "INSTITUTE", value: "i" },
];

export const supervisionOptions = [
    { text: "Project", key: "PROJECT", value: "pro" },
    { text: "Doctorate", key: "DOCTORATE", value: "doc" }
];

export const phdOptions = [
    { text: "Fulltime", key: "FULLTIME", value: "f" },
    { text: "Parttime", key: "PARTTIME", value: "p" }
];

export const graduationOptions = [
    { text: "Matriculate", key: "MATRICULATE", value: "mat" },
    { text: "Intermediate", key: "INTERMEDIATE", value: "int" },
    { text: "Associate", key: "ASSOCIATE", value: "ass" },
    { text: "Graduate", key: "GRADUATE", value: "gra" },
    { text: "Postgraduate", key: "POSTGRADUATE", value: "pos" },
    { text: "Doctorate", key: "DOCTORATE", value: "doc" },
    { text: "Postdoctorate", key: "POSTDOCTORATE", value: "pdo" }
  ];

export const semesterOptions = [
    { text: "Spring", key: "SPRING", value: "s" },
    { text: "Autumn", key: "AUTUMN", value: "a" }
];

export const collaborationOptions = [
    { text: "Undergraduate", key: "UNDERGRADUATE", value: "ug" },
    { text: "Postgraduate", key: "POSTGRADUATE", value: "pg" },
    { text: "PhD", key: "DOCTORATE", value: "phd" },
    { text: "Research Project", key: "RESEARCH_PROJECT", value: "rp" },
    { text: "Other", key: "OTHER", value: "oth" }
];

export const countryOptions = [

    { text: "Afghanistan", key: "AFGHANISTAN", value: "AFGHANISTAN" },
    { text: "Albania", key: "ALBANIA", value: "ALBANIA" },
    { text: "Algeria", key: "ALGERIA", value: "ALGERIA" },
    { text: "American Samoa", key: "AMERICAN_SAMOA", value: "AMERICAN_SAMOA" },
    { text: "Andorra", key: "ANDORRA", value: "ANDORRA" },
    { text: "Angola", key: "ANGOLA", value: "ANGOLA" },
    { text: "Anguilla", key: "ANGUILLA", value: "ANGUILLA" },
    { text: "Antigua and Barbuda", key: "ANTIGUA_AND_BARBUDA", value: "ANTIGUA_AND_BARBUDA" },
    { text: "Argentina", key: "ARGENTINA", value: "ARGENTINA" },
    { text: "Armenia", key: "ARMENIA", value: "ARMENIA" },
    { text: "Aruba", key: "ARUBA", value: "ARUBA" },
    { text: "Australia", key: "AUSTRALIA", value: "AUSTRALIA" },
    { text: "Austria", key: "AUSTRIA", value: "AUSTRIA" },
    { text: "Azerbaijan", key: "AZERBAIJAN", value: "AZERBAIJAN" },
    { text: "Bahamas", key: "BAHAMAS", value: "BAHAMAS" },
    { text: "Bahrain", key: "BAHRAIN", value: "BAHRAIN" },
    { text: "Bangladesh", key: "BANGLADESH", value: "BANGLADESH" },
    { text: "Barbados", key: "BARBADOS", value: "BARBADOS" },
    { text: "Belarus", key: "BELARUS", value: "BELARUS" },
    { text: "Belgium", key: "BELGIUM", value: "BELGIUM" },
    { text: "Belize", key: "BELIZE", value: "BELIZE" },
    { text: "Benin", key: "BENIN", value: "BENIN" },
    { text: "Bermuda", key: "BERMUDA", value: "BERMUDA" },
    { text: "Bhutan", key: "BHUTAN", value: "BHUTAN" },
    { text: "Bolivia", key: "BOLIVIA", value: "BOLIVIA" },
    { text: "Bonaire", key: "BONAIRE", value: "BONAIRE" },
    { text: "Bosnia and Herzegovina", key: "BOSNIA_AND_HERZEGOVINA", value: "BOSNIA_AND_HERZEGOVINA" },
    { text: "Botswana", key: "BOTSWANA", value: "BOTSWANA" },
    { text: "Brazil", key: "BRAZIL", value: "BRAZIL" },
    { text: "British Indian Ocean Ter", key: "BRITISH_INDIAN_OCEAN_TER", value: "BRITISH_INDIAN_OCEAN_TER" },
    { text: "Brunei", key: "BRUNEI", value: "BRUNEI" },
    { text: "Bulgaria", key: "BULGARIA", value: "BULGARIA" },
    { text: "Burkina Faso", key: "BURKINA_FASO", value: "BURKINA_FASO" },
    { text: "Burundi", key: "BURUNDI", value: "BURUNDI" },
    { text: "Cambodia", key: "CAMBODIA", value: "CAMBODIA" },
    { text: "Cameroon", key: "CAMEROON", value: "CAMEROON" },
    { text: "Canada", key: "CANADA", value: "CANADA" },
    { text: "Canary Islands", key: "CANARY_ISLANDS", value: "CANARY_ISLANDS" },
    { text: "Cape Verde", key: "CAPE_VERDE", value: "CAPE_VERDE" },
    { text: "Cayman Islands", key: "CAYMAN_ISLANDS", value: "CAYMAN_ISLANDS" },
    { text: "Central African Republic", key: "CENTRAL_AFRICAN_REPUBLIC", value: "CENTRAL_AFRICAN_REPUBLIC" },
    { text: "Chad", key: "CHAD", value: "CHAD" },
    { text: "Channel Islands", key: "CHANNEL_ISLANDS", value: "CHANNEL_ISLANDS" },
    { text: "Chile", key: "CHILE", value: "CHILE" },
    { text: "China", key: "CHINA", value: "CHINA" },
    { text: "Christmas Island", key: "CHRISTMAS_ISLAND", value: "CHRISTMAS_ISLAND" },
    { text: "Cocos Island", key: "COCOS_ISLAND", value: "COCOS_ISLAND" },
    { text: "Colombia", key: "COLOMBIA", value: "COLOMBIA" },
    { text: "Comoros", key: "COMOROS", value: "COMOROS" },
    { text: "Congo", key: "CONGO", value: "CONGO" },
    { text: "Cook Islands", key: "COOK_ISLANDS", value: "COOK_ISLANDS" },
    { text: "Costa Rica", key: "COSTA_RICA", value: "COSTA_RICA" },
    { text: "Cote DIvoire", key: "COTE_DIVOIRE", value: "COTE_DIVOIRE" },
    { text: "Croatia", key: "CROATIA", value: "CROATIA" },
    { text: "Cuba", key: "CUBA", value: "CUBA" },
    { text: "Curaco", key: "CURACO", value: "CURACO" },
    { text: "Cyprus", key: "CYPRUS", value: "CYPRUS" },
    { text: "Czech Republic", key: "CZECH_REPUBLIC", value: "CZECH_REPUBLIC" },
    { text: "Denmark", key: "DENMARK", value: "DENMARK" },
    { text: "Djibouti", key: "DJIBOUTI", value: "DJIBOUTI" },
    { text: "Dominica", key: "DOMINICA", value: "DOMINICA" },
    { text: "Dominican Republic", key: "DOMINICAN_REPUBLIC", value: "DOMINICAN_REPUBLIC" },
    { text: "East Timor", key: "EAST_TIMOR", value: "EAST_TIMOR" },
    { text: "Ecuador", key: "ECUADOR", value: "ECUADOR" },
    { text: "Egypt", key: "EGYPT", value: "EGYPT" },
    { text: "El Salvador", key: "EL_SALVADOR", value: "EL_SALVADOR" },
    { text: "Equatorial Guinea", key: "EQUATORIAL_GUINEA", value: "EQUATORIAL_GUINEA" },
    { text: "Eritrea", key: "ERITREA", value: "ERITREA" },
    { text: "Estonia", key: "ESTONIA", value: "ESTONIA" },
    { text: "Ethiopia", key: "ETHIOPIA", value: "ETHIOPIA" },
    { text: "Falkland Islands", key: "FALKLAND_ISLANDS", value: "FALKLAND_ISLANDS" },
    { text: "Faroe Islands", key: "FAROE_ISLANDS", value: "FAROE_ISLANDS" },
    { text: "Fiji", key: "FIJI", value: "FIJI" },
    { text: "Finland", key: "FINLAND", value: "FINLAND" },
    { text: "France", key: "FRANCE", value: "FRANCE" },
    { text: "French Guiana", key: "FRENCH_GUIANA", value: "FRENCH_GUIANA" },
    { text: "French Polynesia", key: "FRENCH_POLYNESIA", value: "FRENCH_POLYNESIA" },
    { text: "French Southern Ter", key: "FRENCH_SOUTHERN_TER", value: "FRENCH_SOUTHERN_TER" },
    { text: "Gabon", key: "GABON", value: "GABON" },
    { text: "Gambia", key: "GAMBIA", value: "GAMBIA" },
    { text: "Georgia", key: "GEORGIA", value: "GEORGIA" },
    { text: "Germany", key: "GERMANY", value: "GERMANY" },
    { text: "Ghana", key: "GHANA", value: "GHANA" },
    { text: "Gibraltar", key: "GIBRALTAR", value: "GIBRALTAR" },
    { text: "Great Britain", key: "GREAT_BRITAIN", value: "GREAT_BRITAIN" },
    { text: "Greece", key: "GREECE", value: "GREECE" },
    { text: "Greenland", key: "GREENLAND", value: "GREENLAND" },
    { text: "Grenada", key: "GRENADA", value: "GRENADA" },
    { text: "Guadeloupe", key: "GUADELOUPE", value: "GUADELOUPE" },
    { text: "Guam", key: "GUAM", value: "GUAM" },
    { text: "Guatemala", key: "GUATEMALA", value: "GUATEMALA" },
    { text: "Guinea", key: "GUINEA", value: "GUINEA" },
    { text: "Guyana", key: "GUYANA", value: "GUYANA" },
    { text: "Haiti", key: "HAITI", value: "HAITI" },
    { text: "Hawaii", key: "HAWAII", value: "HAWAII" },
    { text: "Honduras", key: "HONDURAS", value: "HONDURAS" },
    { text: "Hong Kong", key: "HONG_KONG", value: "HONG_KONG" },
    { text: "Hungary", key: "HUNGARY", value: "HUNGARY" },
    { text: "Iceland", key: "ICELAND", value: "ICELAND" },
    { text: "Indonesia", key: "INDONESIA", value: "INDONESIA" },
    { text: "India", key: "INDIA", value: "INDIA" },
    { text: "Iran", key: "IRAN", value: "IRAN" },
    { text: "Iraq", key: "IRAQ", value: "IRAQ" },
    { text: "Ireland", key: "IRELAND", value: "IRELAND" },
    { text: "Isle of Man", key: "ISLE_OF_MAN", value: "ISLE_OF_MAN" },
    { text: "Israel", key: "ISRAEL", value: "ISRAEL" },
    { text: "Italy", key: "ITALY", value: "ITALY" },
    { text: "Jamaica", key: "JAMAICA", value: "JAMAICA" },
    { text: "Japan", key: "JAPAN", value: "JAPAN" },
    { text: "Jordan", key: "JORDAN", value: "JORDAN" },
    { text: "Kazakhstan", key: "KAZAKHSTAN", value: "KAZAKHSTAN" },
    { text: "Kenya", key: "KENYA", value: "KENYA" },
    { text: "Kiribati", key: "KIRIBATI", value: "KIRIBATI" },
    { text: "North Korea", key: "NORTH_KOREA", value: "NORTH_KOREA" },
    { text: "South Korea", key: "SOUTH_KOREA", value: "SOUTH_KOREA" },
    { text: "Kuwait", key: "KUWAIT", value: "KUWAIT" },
    { text: "Kyrgyzstan", key: "KYRGYZSTAN", value: "KYRGYZSTAN" },
    { text: "Laos", key: "LAOS", value: "LAOS" },
    { text: "Latvia", key: "LATVIA", value: "LATVIA" },
    { text: "Lebanon", key: "LEBANON", value: "LEBANON" },
    { text: "Lesotho", key: "LESOTHO", value: "LESOTHO" },
    { text: "Liberia", key: "LIBERIA", value: "LIBERIA" },
    { text: "Libya", key: "LIBYA", value: "LIBYA" },
    { text: "Liechtenstein", key: "LIECHTENSTEIN", value: "LIECHTENSTEIN" },
    { text: "Lithuania", key: "LITHUANIA", value: "LITHUANIA" },
    { text: "Luxembourg", key: "LUXEMBOURG", value: "LUXEMBOURG" },
    { text: "Macau", key: "MACAU", value: "MACAU" },
    { text: "Macedonia", key: "MACEDONIA", value: "MACEDONIA" },
    { text: "Madagascar", key: "MADAGASCAR", value: "MADAGASCAR" },
    { text: "Malaysia", key: "MALAYSIA", value: "MALAYSIA" },
    { text: "Malawi", key: "MALAWI", value: "MALAWI" },
    { text: "Maldives", key: "MALDIVES", value: "MALDIVES" },
    { text: "Mali", key: "MALI", value: "MALI" },
    { text: "Malta", key: "MALTA", value: "MALTA" },
    { text: "Marshall Islands", key: "MARSHALL_ISLANDS", value: "MARSHALL_ISLANDS" },
    { text: "Martinique", key: "MARTINIQUE", value: "MARTINIQUE" },
    { text: "Mauritania", key: "MAURITANIA", value: "MAURITANIA" },
    { text: "Mauritius", key: "MAURITIUS", value: "MAURITIUS" },
    { text: "Mayotte", key: "MAYOTTE", value: "MAYOTTE" },
    { text: "Mexico", key: "MEXICO", value: "MEXICO" },
    { text: "Midway Islands", key: "MIDWAY_ISLANDS", value: "MIDWAY_ISLANDS" },
    { text: "Moldova", key: "MOLDOVA", value: "MOLDOVA" },
    { text: "Monaco", key: "MONACO", value: "MONACO" },
    { text: "Mongolia", key: "MONGOLIA", value: "MONGOLIA" },
    { text: "Montserrat", key: "MONTSERRAT", value: "MONTSERRAT" },
    { text: "Morocco", key: "MOROCCO", value: "MOROCCO" },
    { text: "Mozambique", key: "MOZAMBIQUE", value: "MOZAMBIQUE" },
    { text: "Myanmar", key: "MYANMAR", value: "MYANMAR" },
    { text: "Nambia", key: "NAMBIA", value: "NAMBIA" },
    { text: "Nauru", key: "NAURU", value: "NAURU" },
    { text: "Nepal", key: "NEPAL", value: "NEPAL" },
    { text: "Netherlands Antilles", key: "NETHERLANDS_ANTILLES", value: "NETHERLANDS_ANTILLES" },
    { text: "Netherlands", key: "NETHERLANDS", value: "NETHERLANDS" },
    { text: "Nevis", key: "NEVIS", value: "NEVIS" },
    { text: "New Caledonia", key: "NEW_CALEDONIA", value: "NEW_CALEDONIA" },
    { text: "New Zealand", key: "NEW_ZEALAND", value: "NEW_ZEALAND" },
    { text: "Nicaragua", key: "NICARAGUA", value: "NICARAGUA" },
    { text: "Niger", key: "NIGER", value: "NIGER" },
    { text: "Nigeria", key: "NIGERIA", value: "NIGERIA" },
    { text: "Niue", key: "NIUE", value: "NIUE" },
    { text: "Norfolk Island", key: "NORFOLK_ISLAND", value: "NORFOLK_ISLAND" },
    { text: "Norway", key: "NORWAY", value: "NORWAY" },
    { text: "Oman", key: "OMAN", value: "OMAN" },
    { text: "Pakistan", key: "PAKISTAN", value: "PAKISTAN" },
    { text: "Palau Island", key: "PALAU_ISLAND", value: "PALAU_ISLAND" },
    { text: "Palestine", key: "PALESTINE", value: "PALESTINE" },
    { text: "Panama", key: "PANAMA", value: "PANAMA" },
    { text: "Papua New Guinea", key: "PAPUA_NEW_GUINEA", value: "PAPUA_NEW_GUINEA" },
    { text: "Paraguay", key: "PARAGUAY", value: "PARAGUAY" },
    { text: "Peru", key: "PERU", value: "PERU" },
    { text: "Philippines", key: "PHILIPPINES", value: "PHILIPPINES" },
    { text: "Pitcairn Island", key: "PITCAIRN_ISLAND", value: "PITCAIRN_ISLAND" },
    { text: "Poland", key: "POLAND", value: "POLAND" },
    { text: "Portugal", key: "PORTUGAL", value: "PORTUGAL" },
    { text: "Puerto Rico", key: "PUERTO_RICO", value: "PUERTO_RICO" },
    { text: "Qatar", key: "QATAR", value: "QATAR" },
    { text: "Republic of Montenegro", key: "REPUBLIC_OF_MONTENEGRO", value: "REPUBLIC_OF_MONTENEGRO" },
    { text: "Republic of Serbia", key: "REPUBLIC_OF_SERBIA", value: "REPUBLIC_OF_SERBIA" },
    { text: "Reunion", key: "REUNION", value: "REUNION" },
    { text: "Romania", key: "ROMANIA", value: "ROMANIA" },
    { text: "Russia", key: "RUSSIA", value: "RUSSIA" },
    { text: "Rwanda", key: "RWANDA", value: "RWANDA" },
    { text: "St Bartholemy", key: "ST_BARTHOLEMY", value: "ST_BARTHOLEMY" },
    { text: "St Eustatius", key: "ST_EUSTATIUS", value: "ST_EUSTATIUS" },
    { text: "St Helena", key: "ST_HELENA", value: "ST_HELENA" },
    { text: "St Kitts-Nevis", key: "ST_KITTS_NEVIS", value: "ST_KITTS_NEVIS" },
    { text: "St Lucia", key: "ST_LUCIA", value: "ST_LUCIA" },
    { text: "St Maarten", key: "ST_MAARTEN", value: "ST_MAARTEN" },
    { text: "St Pierre and Miquelon", key: "ST_PIERRE_AND_MIQUELON", value: "ST_PIERRE_AND_MIQUELON" },
    { text: "St Vincent and Grenadines", key: "ST_VINCENT_AND_GRENADINES", value: "ST_VINCENT_AND_GRENADINES" },
    { text: "Saipan", key: "SAIPAN", value: "SAIPAN" },
    { text: "Samoa", key: "SAMOA", value: "SAMOA" },
    { text: "Samoa American", key: "SAMOA_AMERICAN", value: "SAMOA_AMERICAN" },
    { text: "San Marino", key: "SAN_MARINO", value: "SAN_MARINO" },
    { text: "Sao Tome and Principe", key: "SAO_TOME_AND_PRINCIPE", value: "SAO_TOME_AND_PRINCIPE" },
    { text: "Saudi Arabia", key: "SAUDI_ARABIA", value: "SAUDI_ARABIA" },
    { text: "Senegal", key: "SENEGAL", value: "SENEGAL" },
    { text: "Seychelles", key: "SEYCHELLES", value: "SEYCHELLES" },
    { text: "Sierra Leone", key: "SIERRA_LEONE", value: "SIERRA_LEONE" },
    { text: "Singapore", key: "SINGAPORE", value: "SINGAPORE" },
    { text: "Slovakia", key: "SLOVAKIA", value: "SLOVAKIA" },
    { text: "Slovenia", key: "SLOVENIA", value: "SLOVENIA" },
    { text: "Solomon Islands", key: "SOLOMON_ISLANDS", value: "SOLOMON_ISLANDS" },
    { text: "Somalia", key: "SOMALIA", value: "SOMALIA" },
    { text: "South Africa", key: "SOUTH_AFRICA", value: "SOUTH_AFRICA" },
    { text: "Spain", key: "SPAIN", value: "SPAIN" },
    { text: "Sri Lanka", key: "SRI_LANKA", value: "SRI_LANKA" },
    { text: "Sudan", key: "SUDAN", value: "SUDAN" },
    { text: "Suriname", key: "SURINAME", value: "SURINAME" },
    { text: "Swaziland", key: "SWAZILAND", value: "SWAZILAND" },
    { text: "Sweden", key: "SWEDEN", value: "SWEDEN" },
    { text: "Switzerland", key: "SWITZERLAND", value: "SWITZERLAND" },
    { text: "Syria", key: "SYRIA", value: "SYRIA" },
    { text: "Tahiti", key: "TAHITI", value: "TAHITI" },
    { text: "Taiwan", key: "TAIWAN", value: "TAIWAN" },
    { text: "Tajikistan", key: "TAJIKISTAN", value: "TAJIKISTAN" },
    { text: "Tanzania", key: "TANZANIA", value: "TANZANIA" },
    { text: "Thailand", key: "THAILAND", value: "THAILAND" },
    { text: "Togo", key: "TOGO", value: "TOGO" },
    { text: "Tokelau", key: "TOKELAU", value: "TOKELAU" },
    { text: "Tonga", key: "TONGA", value: "TONGA" },
    { text: "Trinidad and Tobago", key: "TRINIDAD_AND_TOBAGO", value: "TRINIDAD_AND_TOBAGO" },
    { text: "Tunisia", key: "TUNISIA", value: "TUNISIA" },
    { text: "Turkey", key: "TURKEY", value: "TURKEY" },
    { text: "Turkmenistan", key: "TURKMENISTAN", value: "TURKMENISTAN" },
    { text: "Turks and Caicos Is", key: "TURKS_AND_CAICOS_IS", value: "TURKS_AND_CAICOS_IS" },
    { text: "Tuvalu", key: "TUVALU", value: "TUVALU" },
    { text: "Uganda", key: "UGANDA", value: "UGANDA" },
    { text: "United Kingdom", key: "UNITED_KINGDOM", value: "UNITED_KINGDOM" },
    { text: "Ukraine", key: "UKRAINE", value: "UKRAINE" },
    { text: "United Arab Emirates", key: "UNITED_ARAB_EMIRATES", value: "UNITED_ARAB_EMIRATES" },
    { text: "United States of America", key: "UNITED_STATES_OF_AMERICA", value: "UNITED_STATES_OF_AMERICA" },
    { text: "Uruguay", key: "URUGUAY", value: "URUGUAY" },
    { text: "Uzbekistan", key: "UZBEKISTAN", value: "UZBEKISTAN" },
    { text: "Vanuatu", key: "VANUATU", value: "VANUATU" },
    { text: "Vatican City State", key: "VATICAN_CITY_STATE", value: "VATICAN_CITY_STATE" },
    { text: "Venezuela", key: "VENEZUELA", value: "VENEZUELA" },
    { text: "Vietnam", key: "VIETNAM", value: "VIETNAM" },
    { text: "Virgin Islands (Brit)", key: "VIRGIN_ISLANDS_BRIT", value: "VIRGIN_ISLANDS_BRIT" },
    { text: "Virgin Islands (USA)", key: "VIRGIN_ISLANDS_USA", value: "VIRGIN_ISLANDS_USA" },
    { text: "Wake Island", key: "WAKE_ISLAND", value: "WAKE_ISLAND" },
    { text: "Wallis and Futana Is", key: "WALLIS_AND_FUTANA_IS", value: "WALLIS_AND_FUTANA_IS" },
    { text: "Yemen", key: "YEMEN", value: "YEMEN" },
    { text: "Zaire", key: "ZAIRE", value: "ZAIRE" },
    { text: "Zambia", key: "ZAMBIA", value: "ZAMBIA" },
    { text: "Zimbabwe", key: "ZIMBABWE", value: "ZIMBABWE" },
    { text: "Korea", key: "KOREA", value: "KOREA" },
    { text: "Serbia", key: "SERBIA", value: "SERBIA" },
]

let list = {};
for (let index in graduationOptions) {
list[graduationOptions[index]["value"]] = graduationOptions[index]["text"];
}

export const graduationOptionsMap = list;

for (let index in supervisionOptions) {
list[supervisionOptions[index]["value"]] = supervisionOptions[index]["text"];
}

export const supervisionOptionsMap = list;
  
export const reduceValueToText = (value, object) => {
    return value == object.value ? object.text : value;
}